name: CI
on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Lint # This might actually be unnecessary because eslint might run as part of the build process, but to be explicit...
        uses: borales/actions-yarn@v4
        with:
          cmd: eslint src
